# Circle starts with version key
version: 2.1

# using orbs will contains list of prepacked circleci configurations
orbs:
  node: circleci/node@5.0.2

jobs:
    build_and_test:
      executor: node/default
      steps:
        - checkout
        - node/install-packages:
            pkg-manager: npm
        - run:
            command:  npm run build
            name: Build App
        - persist_to_workspace:
            root: ~/project
            paths:
              - .

    deploy:
      docker:
        - image: circleci/node:16
      # working_directory:  /app
      steps:
        - checkout
        - setup_remote_docker:
            version: 17.05.0-ce
        - run:
            name: Build and push docker image
            command: |
              docker build -t node-docker .
              echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
              docker tag node-docker:latest "$DOCKER_USERNAME"/node-docker:latest
              docker push "$DOCKER_USERNAME"/node-docker:latest



# workflows:
#   build_test_deploy:
#     jobs:
#       - build-and-test
#       - deploy:
#         requires:
#           - build-and-test
        
#         filters:
#           branches:
#             only: main

workflows:
  build_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: main
        

       
  