# Circle starts with version key
version: 2.1

# using orbs will contains list of prepacked circleci configurations
orbs:
  node: circleci/node@5.0.2
  # aws-ecr: circleci/aws-ecr@8.2.1

jobs:
    # build_and_test:
    #   executor: node/default
    #   steps:
    #     - checkout
    #     - node/install-packages:
    #         pkg-manager: npm
    #     - run:
    #         command:  npm run build
    #         name: Build App
    #     - persist_to_workspace:
    #         root: ~/project
    #         paths:
    #           - .

    # deploy:
    build_and_test:
      docker:
          - image: circleci/node:16
      working_directory: /home/circleci/verity/web
      resource_class: large
      steps:
        - checkout:
            path: /home/circleci/verity/web
        - setup_remote_docker:
            version: 17.05.0-ce
        - run: npm install
        - run: npm run build

          # - run:
          #   name: Build Docker Image
          #   command: docker build -t react-docker .

          # - run:
          #   name: Run Docker Container
          #   command: docker run -d -p 8005:8005 react-docker
          # - run:
          #   name: Run Docker Container
          #   command: docker run -d -p 8005:8005 react-docker
        - run:
            name: Install awscli
            command: |
              sudo apt update
              sudo apt install python3-venv python3-pip
              python3 -m venv venv
              . venv/bin/activate
              pip install awscli

        # - run:
        #       name: Build and push docker image
        #       command: |
        #         eval "docker build -f ./Dockerfile -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/react/docker/web:build-$CIRCLE_BUILD_NUM . "

        - run:
              name: Debug Environment Variables
              command: |
                echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
                echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
                echo "AWS_DEFAULT_REGION: $AWS__REGION"

        - run:
            name: Push image
            command:  |
              . venv/bin/activate

              aws configure list
              
              eval $(aws ecr get-login-password)

              eval "docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/react/docker/web:build-$CIRCLE_BUILD_NUM"

              eval "docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/react/docker/web:build-$CIRCLE_BUILD_NUM $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/react/docker/web:latest"

              eval "docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/react/docker/web:latest"



# workflows:
#   build_test_deploy:
#     jobs:
#       - build-and-test
#       - deploy:
#         requires:
#           - build-and-test
        
#         filters:
#           branches:
#             only: main

workflows:
  build_and_deploy:
    jobs:
      - build_and_test:
            filters:
              branches:
                only: main
        

       
  