# Circle starts with version key
version: 2.1

# using orbs will contains list of prepacked circleci configurations
orbs:
#  node: cricleci/node@5.0.2
#  heroku: circleci/heroku@1.2.6

 jobs:
    build-and-test:
      executor: node/default
      steps:
        - checkout
        - node/install-packages:
            pkg-manager: npm
        - run:
            command:  npm run test
            name: Run tests
        - run:
            command:  npm run build
            name: Build App
        - persist_to_workspace:
            root: ~/project
            paths:
              - .

#     deploy:
#       executor: heroku/default
#       steps:
#         - attach_workspace:
#             at: ~/project
#         - heroku/deploy-via-git:
#             force:  true

# workflows:
#   build_test_deploy:
#     jobs:
#       - build-and-test
#       - deploy:
#         requires:
#           - build-and-test
        
#         filters:
#           branches:
#             only: main
        

       
  