version: 2.1

jobs:
  say-hello:
    docker:
      # Primary image where all steps run
      - image: cimg/base:2022.05
    steps:
      - run: echo "hello this is my first circleci"

  say-bye:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "thank you and bye"

workflows:
  hello-and-bye:
    jobs:
      - say-hello
      - say-bye